<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dineshs-MacBook-Pro.local" ignored="0" name="Test" tests="6" failures="2" timestamp="03 Mar 2019 04:02:31 GMT" time="3.94" errors="0">
  <testcase name="runScenario" time="1.626" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.806" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.332" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status Check Passed - Supposed to be failed!!!">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status Check Passed - Supposed to be failed!!!
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at stepDefinition.test.checkResponseStatusIsNot200(test.java:71)
at ✽.I validate response is not successfull(file:src/test/resources/features/test.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.315" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.288" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.39" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status Check Passed - Supposed to be failed!!!">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status Check Passed - Supposed to be failed!!!
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at stepDefinition.test.checkResponseStatusIsNot200(test.java:71)
at ✽.I validate response is not successfull(file:src/test/resources/features/test2.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
